# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Target < Formula
  desc ""
  homepage "https://github.com/devops-rob/target-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devops-rob/target-cli/releases/download/1.0.0/target-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "537c084cf4bcb6ceff3258bf8792dcaf12d5ddb6353daa3b2cf9a1e9570b6b72"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/1.0.0/target-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "8699a6ff1bffc5f542ff76e7429eacf253b3916facaf1c121565e17b2a719173"

      def install
        bin.install "target"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-rob/target-cli/releases/download/1.0.0/target-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "0227fe26f83670112e1863c50b7fcfcbf767b0e6e05b600844a8885b02bf6935"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/1.0.0/target-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "ddc24546dd430cf047c10c6fdbf928cf00a3e027dc9815593c39f60e5d579222"

      def install
        bin.install "target"
      end
    end
  end
end
