# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Target < Formula
  desc ""
  homepage "https://github.com/devops-rob/target-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devops-rob/target-cli/releases/download/0.4.0/target-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "eb175055249881238b820b9f03c20495bdd69557318d00bbeaddb6696383d568"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/0.4.0/target-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "f3f97768574de709ad4a92c58a22443aa406ba20730b9cf034a20fd872fbc787"

      def install
        bin.install "target"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/0.4.0/target-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "1e9f54a9f6f25a1f85443bbbe4f755525a76c6e77a02e8c5b671cfe20bb1b129"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-rob/target-cli/releases/download/0.4.0/target-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "84d1b1725c5ce9ce16f2c3d3e7460046513c3f6ea12463e355f857780985f237"

      def install
        bin.install "target"
      end
    end
  end
end
