# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Target < Formula
  desc ""
  homepage "https://github.com/devops-rob/target-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devops-rob/target-cli/releases/download/v0.3.0/target-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "09a42b8a9317f7f89cd16830e1533403f3fcf60f8d305be51ccf9b83fb44b945"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/v0.3.0/target-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "9d34bef852b4857d84824d3d4b09d6d106d57b3747b0fa070d3794ff817b15db"

      def install
        bin.install "target"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-rob/target-cli/releases/download/v0.3.0/target-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "dd2e37dff7afc3e4bbe640b400375200f916df5f42017ec2aaff542dd731a6f3"

      def install
        bin.install "target"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-rob/target-cli/releases/download/v0.3.0/target-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "13a6277692905fb59865501912bdc7a45fa37e68d302cf7da67960fcdcf7ff7f"

      def install
        bin.install "target"
      end
    end
  end
end
